import '../styles/logictransparency.css'

export default function LogicTransparency() {
  const insights = [
    {
      id: 1,
      insight: 'Sales increased by 12.5% this week',
      reasoning: 'Compared to last week: 2,543 orders vs 2,257 orders',
      dataPoints: ['Total Orders', 'Time Period', 'Previous Period'],
      confidence: 98,
    },
    {
      id: 2,
      insight: 'Top product is "Premium Widget"',
      reasoning: 'Ranked by total units sold: 324 units (18% of total)',
      dataPoints: ['Product ID', 'Units Sold', 'Category'],
      confidence: 99,
    },
    {
      id: 3,
      insight: 'Customer retention is declining',
      reasoning: 'Returning customers: 45% vs 52% last month',
      dataPoints: ['Customer Status', 'Purchase History', 'Time Period'],
      confidence: 92,
    },
  ]

  return (
    <div className="transparency-page">
      <h1>Logic Transparency (Trust Layer)</h1>
      <p className="subtitle">Understand how AI insights are generated</p>

      <div className="transparency-info">
        <div className="info-card">
          <h3>🤖 How It Works</h3>
          <p>
            Every AI insight is generated by analyzing your data using machine learning models.
            Below, you can see the reasoning and data points behind each insight.
          </p>
        </div>
      </div>

      <div className="insights-list">
        {insights.map((insight) => (
          <div key={insight.id} className="insight-card">
            <div className="insight-header">
              <h3>{insight.insight}</h3>
              <div className="confidence-badge">
                <p>Confidence</p>
                <p className="confidence-value">{insight.confidence}%</p>
              </div>
            </div>

            <div className="insight-content">
              <div className="reasoning">
                <h4>📊 Reasoning:</h4>
                <p>{insight.reasoning}</p>
              </div>

              <div className="data-points">
                <h4>📈 Data Points Used:</h4>
                <ul>
                  {insight.dataPoints.map((point, idx) => (
                    <li key={idx}>{point}</li>
                  ))}
                </ul>
              </div>

              <div className="confidence-bar">
                <h4>Confidence Score:</h4>
                <div className="progress">
                  <div
                    className="progress-fill"
                    style={{ width: `${insight.confidence}%` }}
                  />
                </div>
              </div>
            </div>

            <div className="insight-footer">
              <button className="btn-learn-more">Learn More →</button>
              <button className="btn-verify">Verify Data</button>
            </div>
          </div>
        ))}
      </div>

      <div className="methodology">
        <h3>🔬 AI Methodology</h3>
        <div className="methodology-steps">
          <div className="step">
            <h4>1. Data Collection</h4>
            <p>AI collects data from your orders, products, and customers</p>
          </div>
          <div className="step">
            <h4>2. Data Cleaning</h4>
            <p>Removes duplicates, handles missing values, normalizes formats</p>
          </div>
          <div className="step">
            <h4>3. Analysis</h4>
            <p>Applies statistical analysis and machine learning algorithms</p>
          </div>
          <div className="step">
            <h4>4. Insight Generation</h4>
            <p>Generates human-readable insights with confidence scores</p>
          </div>
        </div>
      </div>
    </div>
  )
}
